spring:
  profiles:
    active:
    - dev
    
---   #三个-号作分割

spring:
  profiles: dev		#开发环境
  application:
    name: microservicecloud-config-myj-dev
    
---

spring:
  profiles: test		#测试环境
  application:
    name: microservicecloud-config-myj-test
# 注意保存为UTF-8格式?
